# Generated by Django 3.0.6 on 2020-05-08 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bazaar_orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('ordersNum', models.IntegerField()),
                ('pricePerUnit', models.FloatField()),
                ('item_id', models.CharField(max_length=255)),
                ('item_name', models.CharField(max_length=255)),
            ],
        ),
    ]
